### ISSUE TITLE
OSIS Links to general books do not work

### ISSUE THREAD

**Issue by tuomas2** [mjdenham/and-bible#23]
I fail to get links within genbook (and from a commentary to genbook) work. Here, for example, in OSIS, my link reads:

```
<reference osisRef="ESVN_articles:Book_introductions/Introduction_to_Genesis/Genesis_and_Science">...</reference>
```

Otherwise module seems to work fine, and links to bible are OK. Links work fine with Xiphos, but with with BibleDesktop I also had problems, but not the same error message.

Error message from adb logcat:
```
D/net.bible.service.sword.SwordDocumentFacade(28555): Getting book:ESVN_articles
E/LinkControl(28555): Error going to link
E/LinkControl(28555): 	at net.bible.android.control.link.LinkControl.showSpecificDocRef(LinkControl.java:111)
E/LinkControl(28555): 	at net.bible.android.control.link.LinkControl.loadApplicationUrl(LinkControl.java:79)
E/LinkControl(28555): 	at net.bible.android.view.activity.page.BibleView$1.shouldOverrideUrlLoading(BibleView.java:95)
E/LinkControl(28555): 	at com.android.webview.chromium.WebViewContentsClientAdapter.shouldOverrideUrlLoading(WebViewContentsClientAdapter.java:299)
E/LinkControl(28555): 	at com.android.org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:95)
E/LinkControl(28555): 	at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
E/LinkControl(28555): 	at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:24)
E/LinkControl(28555): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/LinkControl(28555): 	at android.os.Looper.loop(Looper.java:136)
E/LinkControl(28555): 	at android.app.ActivityThread.main(ActivityThread.java:5034)
E/LinkControl(28555): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/LinkControl(28555): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/LinkControl(28555): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
E/LinkControl(28555): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
E/LinkControl(28555): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
E/LinkControl(28555): 	at dalvik.system.NativeStart.main(Native Method)
D/BibleView(28555): onLoadResource:sword://ESVN_articles/Book_introductions/Introduction_to_Genesis/Genesis_and_Science
E/BibleView(28555): net::ERR_UNKNOWN_URL_SCHEME
```

**Comment by mjdenham** [comment]
I think the structure should be:

sword://modulename/key

**Comment by tuomas2** [comment]
When going there via chapter selector (which works) it prints to logcat:

```
D/UpdateTextTask(19400): Loading html in background
D/UpdateTextTask(19400): Loading document:ESVN_articles key:Book_introductions.Introduction_to_Genesis.Author__Title__and_Date
D/net.bible.service.sword.SwordContentFacade(19400): Using standard JSword to fetch document data
I/net.bible.android.view.activity.navigation.genbookmap.ChooseGeneralBookKey(19400): onPause:net.bible.android.view.activity.navigation.genbookmap.ChooseGeneralBookKey@421b35a8
D/MainBibleActivity(19400): Activity result:99
I/net.bible.android.view.activity.page.MainBibleActivity(19400): onRestart:net.bible.android.view.activity.page.MainBibleActivity@421b59c8
I/net.bible.android.view.activity.page.MainBibleActivity(19400): onStart:net.bible.android.view.activity.page.MainBibleActivity@421b59c8
I/net.bible.android.view.activity.page.MainBibleActivity(19400): onResume:net.bible.android.view.activity.page.MainBibleActivity@421b59c8
D/net.bible.service.font.FontControl(19400): Book:ESVN_articles Language code:en Font:null
```

So the correct structure internally seems to be sword://modulename/rootnode.somethingbetween.leafnode instead of 
sword://modulename/rootnode/somethingbetween/leafnode. 

Now that I look at  http://www.crosswire.org/wiki/OSIS_Genbooks#Scripture_References_and_Other_Links
I notice that my OSIS should be like
```
<reference osisRef="ESVN_articles:Book_introductions.Introduction_to_Genesis.Genesis_and_Science">...</reference>
```
When I try this way formatted links, it still does not work, and I get in logcat: 

```
D/LinkControl(31227): Loading: sword://ESVN_articles/Book_introductions.Introduction_to_Genesis.Author__Title__and_Date
D/net.bible.service.sword.SwordDocumentFacade(31227): Getting book:ESVN_articles
E/LinkControl(31227): Error going to link
E/LinkControl(31227): org.crosswire.jsword.passage.NoSuchKeyException: No entry for 'Book_introductions.Introduction_to_Genesis.Author__Title__and_Date' in ESVN_articles.
E/LinkControl(31227): 	at org.crosswire.jsword.book.sword.SwordGenBook.getKey(SwordGenBook.java:234)
E/LinkControl(31227): 	at net.bible.android.control.link.LinkControl.showSpecificDocRef(LinkControl.java:111)
E/LinkControl(31227): 	at net.bible.android.control.link.LinkControl.loadApplicationUrl(LinkControl.java:79)
E/LinkControl(31227): 	at net.bible.android.view.activity.page.BibleView$1.shouldOverrideUrlLoading(BibleView.java:95)
E/LinkControl(31227): 	at com.android.webview.chromium.WebViewContentsClientAdapter.shouldOverrideUrlLoading(WebViewContentsClientAdapter.java:299)
E/LinkControl(31227): 	at com.android.org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:95)
E/LinkControl(31227): 	at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
E/LinkControl(31227): 	at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:24)
E/LinkControl(31227): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/LinkControl(31227): 	at android.os.Looper.loop(Looper.java:136)
E/LinkControl(31227): 	at android.app.ActivityThread.main(ActivityThread.java:5034)
E/LinkControl(31227): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/LinkControl(31227): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/LinkControl(31227): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
E/LinkControl(31227): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
E/LinkControl(31227): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
E/LinkControl(31227): 	at dalvik.system.NativeStart.main(Native Method)
D/BibleView(31227): onLoadResource:sword://ESVN_articles/Book_introductions.Introduction_to_Genesis.Author__Title__and_Date
E/BibleView(31227): net::ERR_UNKNOWN_URL_SCHEME
```

(and BTW, now Xiphos does not work any more :P)

**Comment by mjdenham** [comment]
Hi Tuomas,

Could you raise all these issues in the discussion group because I am the only person who looks here.

Thanks
Martin

**Comment by tuomas2** [comment]
Found bug in jsword and fixed it in https://github.com/crosswire/jsword/pull/98

**Comment by tuomas2** [comment]
From libsword source I (treekeyidx.cpp:517 i.e. TreeKeyIdx.setText()) can read that the current sword implementation requires key in slash format (i.e. ESVN_articles:Book_introductions/Introduction_to_Genesis/Genesis_and_Science). If I understand correctly, libsword is the reference implementation which jsword should conform, so I need to fix that still. Or is genbook osisRef syntax defined by OSIS standard? Not if I see it correctly.

Please tell if my assumption is not correct. Continuing tomorrow.. ;)

**Comment by tuomas2** [comment]
Let's close this and move discussion to https://github.com/crosswire/jsword/pull/98
