### ISSUE TITLE
Error when viewing MyNotes: IllegalArgumentException: Comparison method violates its general contract!

### ISSUE THREAD

**Issue by mjdenham** [mjdenham/and-bible#86]
Not sure if it is the MYNote creation date or bible order comparator that is in error.

My suspicion is that ConvertibleVerseRange.compareTo compares inconsistently (and generates error) where one of the verses does not exist in the versification of the other verse e.g. if one verse is deuterocanonical and the other verse from the KJV.

One possible solution would be to convert all verses to nrsv before comparison, which contains all books (I think).

For now I have wrapped the sort in a try/catch to prevent And Bible crashing when displaying Notes.

This is the error seen in Play Store logs.

java.lang.RuntimeException: Unable to start activity ComponentInfo{net.bible.android.activity/net.bible.android.view.activity.mynote.MyNotes}: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2317)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2375)
	at android.app.ActivityThread.access$900(ActivityThread.java:164)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1268)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:157)
	at android.app.ActivityThread.main(ActivityThread.java:5377)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeLo(TimSort.java:743)
	at java.util.TimSort.mergeAt(TimSort.java:479)
	at java.util.TimSort.mergeForceCollapse(TimSort.java:422)
	at java.util.TimSort.sort(TimSort.java:219)
	at java.util.TimSort.sort(TimSort.java:169)
	at java.util.Arrays.sort(Arrays.java:2023)
	at java.util.Collections.sort(Collections.java:1883)
	at net.bible.android.control.mynote.MyNoteControl.getSortedMyNotes(MyNoteControl.java:303)
	at net.bible.android.control.mynote.MyNoteControl.getAllMyNotes(MyNoteControl.java:174)
	at net.bible.android.view.activity.mynote.MyNotes.loadUserNoteList(MyNotes.java:175)
	at net.bible.android.view.activity.mynote.MyNotes.initialiseView(MyNotes.java:71)
	at net.bible.android.view.activity.mynote.MyNotes.onCreate(MyNotes.java:58)
	at android.app.Activity.performCreate(Activity.java:5428)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2281)

**Comment by mjdenham** [comment]
Have done a lot more work on this.

1. Get bookmark/note versifications
2. Order v11ns by frequency
3. When comparing verses, first convert to the most preferred v11n containing both verses

This will hopefully ensure that verses are compared consistently whether comparing v1 with v2 or v2 with v1.  Also there is a higher probability of being able to compare all verses.

However, it is still possible 2 verses may not exist in a single v11n but hopefully, even then sorting will be consistent.
